language: node_js
before_script:
  - npm install -g bower
script:
  - bash ./deploy-to-gh-pages.sh
env:
  global:
    - GITHUB_REPO: "Ramotion/aquarelle"
    - secure: "jbYrk4ft6krPuSanHopdtgUAUknFVS1m0+fokfS9FJWhsuOqmfP59EKF4mQpPk2ywLIu25NxPF6PuK26sk+8JVmiI4a+ycQIgjjbo/SStzJBy6mCTuXDjU1jJN8W3z20yf3+ltFtJuPmrE6nTZ+FAhmRk/Fp/A2TjjQsmz+ZlnCjTWjuiLEEkXY9nkqrceftUBt4BvHRcqn3vWp8ipDAiP52MJ9lArk4nHe6URcAvURk4QEuQ6bu8hRyysI8/ukSnVFHD4vYvn1T2ed5U3KgJqiayVJD32epSyYFixx+aLpwmJyMTrRpOkjCoxNwn6yDN4sKHuox5pUyWP2wzdSCvJCTrwHc2N+End5/n9YTOTM2UX75mtaMRTsg+lrngg3rQvCjdxGMXD4uM6u1r1KLvocYjOSM4P1sttV7g3Tu/Gmp5BCYC++snoG3SDlbfu2shtf8gARO7MnM5lpo8+NnkBT2NtUh9/g5RAbUkXbNLqs4pFhdg7wN/ieRLPqRIWK5d/zJZfGsUpLtqLrqfXZOU4nrxF6quGfTKJ1zdFj6GQIKvbfr7YQSVa79121Khmfb2xDX8/SLb/D5qVbF4pxXX3lpzVT9qXFVqLlBLCoBpH7XPvM1ys6v06VvZN8ML2TyMVSe43oTvQoFip6t2ss+RTN+4+Y2oHgaTk2gw9uo9gU="